In [2]:
import pandas as pd
import numpy as np

In [6]:
file_path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_base.csv"

In [9]:
df = pd.read_csv(file_path, header = None)
df.head(5)

     0   1          2   3   4   5       6    7   8    9     10    11
0  Acer   4  IPS Panel   2   1   5   35.56  1.6   8  256   1.6   978
1  Dell   3    Full HD   1   1   3  39.624  2.0   4  256   2.2   634
2  Dell   3    Full HD   1   1   7  39.624  2.7   8  256   2.2   946
3  Dell   4  IPS Panel   2   1   5  33.782  1.6   8  128  1.22  1244
4    HP   4    Full HD   2   1   7  39.624  1.8   8  256  1.91   837

In [11]:
headers = ['Manufacturer', 'Category', 'screen', 'GPU', 'Os', 'CPU_Core', 'Screen_size_cm', 'CPU_Frequency', 'Ram_GB', 'Storage_GB_SSD', 'Weight_Kg', 'Price']
df.columns = headers
df.head(10)

,Manufacturer,Category,screen,GPU,Os,CPU_Core,Screen_size_cm,CPU_Frequency,Ram_GB,Storage_GB_SSD,Weight_Kg,Price
0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.6,978
1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
5,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016
6,HP,3,Full HD,3,1,5,39.624,1.6,8,256,2.1,1117
7,Acer,3,IPS Panel,2,1,5,38.1,1.6,4,256,2.2,866
8,Dell,3,Full HD,1,1,5,39.624,2.5,4,256,2.3,812
9,Acer,3,IPS Panel,3,1,7,38.1,1.8,8,256,2.2,1068

In [12]:
df = df.replace("?", np.nan, inplace = True)

In [15]:
df.dtypes

Manufacturer          str
Category            int64
screen                str
GPU                 int64
Os                  int64
CPU_Core            int64
Screen_size_cm        str
CPU_Frequency     float64
Ram_GB              int64
Storage_GB_SSD      int64
Weight_Kg             str
Price               int64
dtype: object

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    238 non-null    str
 1   Category        238 non-null    int64
 2   screen          238 non-null    str
 3   GPU             238 non-null    int64
 4   Os              238 non-null    int64
 5   CPU_Core        238 non-null    int64
 6   Screen_size_cm  234 non-null    str
 7   CPU_Frequency   238 non-null    float64
 8   Ram_GB          238 non-null    int64
 9   Storage_GB_SSD  238 non-null    int64
 10  Weight_Kg       233 non-null    str
 11  Price           238 non-null    int64
dtypes: float64(1), int64(7), str(4)
memory usage: 22.4 KB